import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">Go home</Link>
        <Link href="/login" style={{ marginLeft: '0.4rem' }}>
          Go to login
        </Link>
        <Link href="/protected-rsc" style={{ marginLeft: '0.4rem' }}>
          Go to protected RSC
        </Link>
        <div style={{ marginTop: '1rem' }}>{children}</div>
      </body>
    </html>
  );
}
